INSERT INTO Provinces VALUES ('1', 'Buenos Aires');
INSERT INTO Provinces VALUES ('2', 'Capital Federal');
INSERT INTO Provinces VALUES ('3', 'Catamarca');
INSERT INTO Provinces VALUES ('4', 'Chaco');
INSERT INTO Provinces VALUES ('5', 'Chubut');
INSERT INTO Provinces VALUES ('6', 'Cordoba');
INSERT INTO Provinces VALUES ('7', 'Corrientes');
INSERT INTO Provinces VALUES ('8', 'Entre Rios');
INSERT INTO Provinces VALUES ('9', 'Formosa');
INSERT INTO Provinces VALUES ('10', 'Jujuy');
INSERT INTO Provinces VALUES ('11', 'La Pampa');
INSERT INTO Provinces VALUES ('12', 'La Rioja');
INSERT INTO Provinces VALUES ('13', 'Mendoza');
INSERT INTO Provinces VALUES ('14', 'Misiones');
INSERT INTO Provinces VALUES ('15', 'Neuquen');
INSERT INTO Provinces VALUES ('16', 'Rio Negro');
INSERT INTO Provinces VALUES ('17', 'Salta');
INSERT INTO Provinces VALUES ('18', 'San Juan');
INSERT INTO Provinces VALUES ('19', 'San Luis');
INSERT INTO Provinces VALUES ('20', 'Santa Cruz');
INSERT INTO Provinces VALUES ('21', 'Santa Fe');
INSERT INTO Provinces VALUES ('22', 'Santiago del Estero');
INSERT INTO Provinces VALUES ('23', 'Tierra del Fuego');
INSERT INTO Provinces VALUES ('24', 'Tucuman');